#!/usr/bin/env python3
"""Deep-research sidecar.

This is the process boundary used by the Obsidian plugin. It reads a run.json
file, advances progress in run.json/status.json, and writes report.md.

If langchain-ai/open_deep_research is installed in this Python environment, use
`--engine open_deep_research` or `--engine auto` to run its LangGraph. Otherwise
the script falls back to a deterministic stub so the Obsidian UX stays testable.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import contextlib
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

Engine = Literal["auto", "stub", "open_deep_research"]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value: dict[str, Any]) -> None:
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")


def write_status(run_path: Path, record: dict[str, Any]) -> None:
    status_path = run_path.parent / "status.json"
    write_json(
        status_path,
        {
            "id": record["id"],
            "status": record["status"],
            "progress": record["progress"],
            "reportPath": record["reportPath"],
            "updatedAt": record["updatedAt"],
        },
    )


def update_progress(run_path: Path, record: dict[str, Any], step: str, message: str, percent: int) -> None:
    record["status"] = step
    record["progress"] = {
        "step": step,
        "message": message,
        "percent": percent,
    }
    record["updatedAt"] = now_iso()
    write_json(run_path, record)
    write_status(run_path, record)


def write_report(vault: Path, record: dict[str, Any]) -> None:
    report_path = vault / record["reportPath"]
    report_path.parent.mkdir(parents=True, exist_ok=True)
    context = record["request"].get("context", "").strip() or "No context supplied."
    report_path.write_text(
        "\n".join(
            [
                f"# Deep research: {record['noteTitle']}",
                "",
                "> Stub report generated by the Python sidecar contract test.",
                "",
                "## Research brief",
                "",
                context,
                "",
                "## Backend integration",
                "",
                "Install langchain-ai/open_deep_research and run this sidecar with `--engine open_deep_research`.",
                "",
            ],
        ),
        encoding="utf-8",
    )


def run_stub(vault: Path, run_path: Path, record: dict[str, Any]) -> int:
    steps = [
        ("planning", "Planning search strategy in sidecar.", 15),
        ("searching", "Sidecar stub search complete.", 40),
        ("fetching", "Sidecar stub source collection complete.", 65),
        ("synthesizing", "Sidecar stub writing report.", 85),
    ]

    try:
        for step, message, percent in steps:
            time.sleep(0.8)
            update_progress(run_path, record, step, message, percent)

        write_report(vault, record)
        update_progress(run_path, record, "completed", "Sidecar stub deep research report completed.", 100)
        return 0
    except Exception as exc:
        update_progress(run_path, record, "failed", str(exc), record.get("progress", {}).get("percent", 0))
        return 1


async def run_open_deep_research(vault: Path, run_path: Path, record: dict[str, Any]) -> int:
    try:
        # Imports stay inside the function so the stub works without these deps.
        from langchain_core.messages import HumanMessage
        from open_deep_research.deep_researcher import deep_researcher
    except Exception as exc:
        update_progress(
            run_path,
            record,
            "failed",
            f"Open Deep Research is not importable in this Python environment: {exc}",
            record.get("progress", {}).get("percent", 0),
        )
        return 1

    try:
        update_progress(run_path, record, "planning", "Starting Open Deep Research graph.", 10)
        request = record.get("request", {})
        context = request.get("context", "").strip()
        model = model_for_open_deep_research(request)

        configurable = {
            "allow_clarification": False,
            "research_model": model,
            "summarization_model": os.environ.get("RESEARCHER_SUMMARIZATION_MODEL", model),
            "compression_model": os.environ.get("RESEARCHER_COMPRESSION_MODEL", model),
            "final_report_model": os.environ.get("RESEARCHER_FINAL_REPORT_MODEL", model),
            "search_api": os.environ.get("RESEARCHER_SEARCH_API", "tavily"),
            "max_researcher_iterations": int(os.environ.get("RESEARCHER_MAX_ITERATIONS", "4")),
            "max_react_tool_calls": int(os.environ.get("RESEARCHER_MAX_TOOL_CALLS", "8")),
            "max_concurrent_research_units": int(os.environ.get("RESEARCHER_MAX_CONCURRENCY", "4")),
        }

        update_progress(run_path, record, "searching", "Open Deep Research is gathering evidence.", 35)
        heartbeat = asyncio.create_task(progress_heartbeat(run_path, record))
        try:
            result = await deep_researcher.ainvoke(
                {"messages": [HumanMessage(content=context)]},
                {"configurable": configurable},
            )
        finally:
            heartbeat.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await heartbeat

        update_progress(run_path, record, "synthesizing", "Writing Open Deep Research report.", 85)
        report = extract_report(result)
        write_open_deep_research_report(vault, record, report, result)
        update_progress(run_path, record, "completed", "Open Deep Research report completed.", 100)
        return 0
    except Exception as exc:
        update_progress(run_path, record, "failed", str(exc), record.get("progress", {}).get("percent", 0))
        return 1


async def progress_heartbeat(run_path: Path, record: dict[str, Any]) -> None:
    started = time.monotonic()
    messages = [
        "Open Deep Research is gathering and checking sources.",
        "Open Deep Research is delegating focused research tasks.",
        "Open Deep Research is compressing intermediate findings.",
        "Open Deep Research is preparing evidence for synthesis.",
    ]
    index = 0

    while True:
        await asyncio.sleep(10)
        elapsed_minutes = int((time.monotonic() - started) // 60)
        percent = min(80, 35 + (index + 1) * 3)
        update_progress(
            run_path,
            record,
            "searching",
            f"{messages[index % len(messages)]} Elapsed: {elapsed_minutes} min.",
            percent,
        )
        index += 1


def model_for_open_deep_research(request: dict[str, Any]) -> str:
    env_model = os.environ.get("RESEARCHER_RESEARCH_MODEL")
    if env_model:
        return env_model

    model = str(request.get("llmModel") or "").strip()
    provider = request.get("llmProvider")
    if not model:
        return "openai:gpt-4.1"
    if provider == "ollama":
        return f"ollama:{model}"
    return model


def extract_report(result: Any) -> str:
    if isinstance(result, dict):
        report = result.get("final_report")
        if isinstance(report, str) and report.strip():
            return report
        messages = result.get("messages")
        if isinstance(messages, list) and messages:
            content = getattr(messages[-1], "content", None)
            if isinstance(content, str) and content.strip():
                return content
    return json.dumps(result, default=str, indent=2)


def write_open_deep_research_report(vault: Path, record: dict[str, Any], report: str, result: Any) -> None:
    report_path = vault / record["reportPath"]
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report.rstrip() + "\n", encoding="utf-8")

    raw_path = report_path.parent / "open-deep-research-result.json"
    raw_path.write_text(json.dumps(result, default=str, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--vault", required=True, help="Absolute path to the Obsidian vault.")
    parser.add_argument("--run", required=True, help="Absolute path to run.json.")
    parser.add_argument(
        "--engine",
        choices=["auto", "stub", "open_deep_research"],
        default=os.environ.get("RESEARCHER_SIDECAR_ENGINE", "auto"),
        help="Research backend to run. auto tries Open Deep Research and falls back to stub.",
    )
    args = parser.parse_args()

    vault = Path(args.vault)
    run_path = Path(args.run)
    record = read_json(run_path)
    engine: Engine = args.engine

    if engine == "stub":
        return run_stub(vault, run_path, record)

    if engine == "open_deep_research":
        return asyncio.run(run_open_deep_research(vault, run_path, record))

    try:
        import open_deep_research  # noqa: F401
    except Exception:
        return run_stub(vault, run_path, record)
    return asyncio.run(run_open_deep_research(vault, run_path, record))


if __name__ == "__main__":
    raise SystemExit(main())
