"""Interactive first-time setup wizard. Entry point: `ai-os setup`."""

from __future__ import annotations

import sys
from pathlib import Path

from .config import user_config_dir

_CONFIG_TEMPLATE = """\
# AI OS configuration — generated by `ai-os setup`.
# Edit this file to tune models or paths.

[vault]
# Absolute path to your Obsidian vault.
path = {vault_path!r}
inbox_dirs = ["00_Inbox", "01_Fleeting"]

[storage]
data_dir = {data_dir!r}
duckdb_path = "${{data_dir}}/index.duckdb"
lightrag_dir = "${{data_dir}}/lightrag"

[inference]
base_url = "http://localhost:11434/v1"
api_key = "ollama"
synthesis_model = {synthesis_model!r}
embedding_model = {embedding_model!r}
judge_model = {judge_model!r}
timeout_s = 300

[watcher]
debounce_ms = 500
ignore_globs = [".obsidian/**", ".trash/**", ".git/**"]

[server]
host = "127.0.0.1"
port = 8765
"""

_MODELS = {
    "synthesis": {
        "default": "qwen2.5:14b-instruct",
        "options": [
            ("qwen2.5:14b-instruct", "~9 GB — best quality"),
            ("qwen2.5:7b-instruct", "~4.7 GB — faster, lower quality"),
            ("llama3.2:3b", "~2 GB — minimal hardware"),
        ],
    },
    "embedding": {
        "default": "nomic-embed-text",
        "options": [
            ("nomic-embed-text", "768-dim, recommended"),
            ("mxbai-embed-large", "1024-dim, higher quality"),
        ],
    },
    "judge": {
        "default": "qwen2.5:7b-instruct",
        "options": [
            ("qwen2.5:7b-instruct", "~4.7 GB — recommended"),
            ("llama3.2:3b", "~2 GB — faster"),
        ],
    },
}


def _prompt(label: str, default: str) -> str:
    try:
        value = input(f"  {label} [{default}]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        sys.exit(1)
    return value or default


def _pick(label: str, options: list[tuple[str, str]], default: str) -> str:
    print(f"\n  {label}:")
    for i, (name, desc) in enumerate(options, 1):
        marker = " (default)" if name == default else ""
        print(f"    {i}) {name}  — {desc}{marker}")
    raw = _prompt("Choice (number or name)", default)
    if raw.isdigit():
        idx = int(raw) - 1
        if 0 <= idx < len(options):
            return options[idx][0]
    return raw


def setup(yes: bool = False, vault: str | None = None) -> None:
    """Interactive setup: writes config.toml to the user config directory.

    Pass yes=True with a vault path to skip all prompts and use defaults.
    """
    print()
    print("AI OS Setup Wizard")
    print("==================")
    if yes:
        print("Using defaults (--yes mode).\n")
    else:
        print("This creates a config.toml in your user config directory.")
        print("Press Enter to accept defaults.\n")

    # Vault path
    print("── Vault ────────────────────────────────────────────")
    default_vault = str(Path.home() / "Documents" / "Vault")
    if yes:
        vault_path = str(Path(vault or default_vault).expanduser().resolve())
        print(f"  Vault path: {vault_path}")
    else:
        vault_path = _prompt("Absolute path to your Obsidian vault", vault or default_vault)
        vault_path = str(Path(vault_path).expanduser().resolve())

    # Models
    print("\n── Models ───────────────────────────────────────────")
    if yes:
        synthesis_model = _MODELS["synthesis"]["default"]
        embedding_model = _MODELS["embedding"]["default"]
        judge_model = _MODELS["judge"]["default"]
        print(f"  Synthesis : {synthesis_model}")
        print(f"  Embedding : {embedding_model}")
        print(f"  Judge     : {judge_model}")
    else:
        print("  (Models are pulled from Ollama. See https://ollama.ai)")
        synthesis_model = _pick(
            "Synthesis model (long-form research reports)",
            _MODELS["synthesis"]["options"],
            _MODELS["synthesis"]["default"],
        )
        embedding_model = _pick(
            "Embedding model (semantic search)",
            _MODELS["embedding"]["options"],
            _MODELS["embedding"]["default"],
        )
        judge_model = _pick(
            "Judge model (citation verification)",
            _MODELS["judge"]["options"],
            _MODELS["judge"]["default"],
        )

    # Write config
    cfg_dir = user_config_dir()
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = cfg_dir / "config.toml"
    data_dir = str(cfg_dir)

    if cfg_path.exists():
        print(f"\n  Config already exists at: {cfg_path}")
        if yes:
            print("  Overwriting (--yes).")
        else:
            overwrite = _prompt("Overwrite? (y/n)", "n")
            if overwrite.lower() not in ("y", "yes"):
                print("Aborted — existing config unchanged.")
                sys.exit(0)

    config_text = _CONFIG_TEMPLATE.format(
        vault_path=vault_path,
        data_dir=data_dir,
        synthesis_model=synthesis_model,
        embedding_model=embedding_model,
        judge_model=judge_model,
    )
    cfg_path.write_text(config_text, encoding="utf-8")

    print(f"\n  Config written to: {cfg_path}")
    print()
    print("── Next steps ───────────────────────────────────────")
    print("  1. Pull your models (if not already downloaded):")
    print(f"       ollama pull {embedding_model}")
    print(f"       ollama pull {judge_model}")
    if synthesis_model != judge_model:
        print(f"       ollama pull {synthesis_model}")
    print()
    print("  2. Index your vault:")
    print("       ai-os ingest")
    print()
    print("  3. Start the backend:")
    print("       ai-os serve")
    print()
    print("  4. In Obsidian, go to Settings → AI OS → Check connection.")
    print()
